#include "ObjectSchemaBuilder.hpp"
#include "RapidJsonUtilty.hpp"

#include <algorithm>
#include <gtest/gtest.h>

// Test to verify that schemas generated by ObjectSchemaBuilder are actually parseable by rapidjson
TEST(ObjectSchemaBuilderValidationTest, SchemaParseabilityTest) {
  // Create a schema similar to what's used in RokuHttp.cpp
  constexpr auto rokuSchemaBuilder = ObjectSchema()
                                         .Require("ip_address", "string")
                                         .Require("name", "string");

  constexpr auto schemaString = rokuSchemaBuilder.Build();
  ASSERT_NE(schemaString.data(), nullptr);
  ASSERT_GT(schemaString.size(), 0);

  // Test that we can parse the generated schema using OMOTE::JSON::GetDocument
  // This validates that schemas are properly formed JSON that rapidjson can work with
  auto schemaDocument = OMOTE::JSON::GetDocument(schemaString);

  // Should be a valid document (at least the structure is there)
  ASSERT_TRUE(schemaDocument.IsObject());
  ASSERT_TRUE(schemaDocument.HasMember("type"));
  ASSERT_TRUE(schemaDocument["type"].IsString());
  ASSERT_STREQ(schemaDocument["type"].GetString(), "object");

  ASSERT_TRUE(schemaDocument.HasMember("required"));
  ASSERT_TRUE(schemaDocument["required"].IsArray());

  ASSERT_TRUE(schemaDocument.HasMember("properties"));
  ASSERT_TRUE(schemaDocument["properties"].IsObject());
}

// Test to verify generated schemas can validate sample JSON data
TEST(ObjectSchemaBuilderValidationTest, SchemaValidationIntegrationTest) {
  // Create a schema builder similar to RokuHttp.cpp
  constexpr auto rokuSchemaBuilder = ObjectSchema()
                                         .Require("ip_address", "string")
                                         .Require("name", "string");

  constexpr auto schemaString = rokuSchemaBuilder.Build();
  ASSERT_NE(schemaString.data(), nullptr);

  // Parse the generated schema
  auto schemaDocument = OMOTE::JSON::GetDocument(schemaString);
  ASSERT_TRUE(schemaDocument.IsObject());

  // Test a valid configuration
  std::string validConfigJson = R"({
    "ip_address": "192.168.1.100",
    "name": "My Roku"
  })";

  auto validConfig = OMOTE::JSON::GetDocument(validConfigJson);
  ASSERT_TRUE(validConfig.IsObject());

  // Test an invalid configuration (missing required field)
  std::string invalidConfigJson = R"({
    "ip_address": "192.168.1.100"
  })";

  auto invalidConfig = OMOTE::JSON::GetDocument(invalidConfigJson);
  ASSERT_TRUE(invalidConfig.IsObject());

  // Test that the validation actual works as intended
  rapidjson::SchemaDocument schema(schemaDocument);
  rapidjson::SchemaValidator validator(schema);
  ASSERT_TRUE(validConfig.Accept(validator));    // Should pass validation
  ASSERT_FALSE(invalidConfig.Accept(validator)); // Should fail validation due to missing "name
}