#include "ObjectSchemaBuilder.hpp"
#include "RapidJsonUtilty.hpp"

#include <algorithm>
#include <gtest/gtest.h>

constexpr auto rokuSchema = OMOTE::JSON::ObjectSchema()
                                .Require("ip_address", "string")
                                .Require("name", "string")
                                .Build();

// Test to verify that schemas generated by ObjectSchemaBuilder are actually parseable by rapidjson
TEST(ObjectSchemaBuilderValidationTest, SchemaParseAbilityTest) {
  // Create a schema similar to what's used in RokuHttp.cpp

  ASSERT_NE(rokuSchema.data(), nullptr);
  ASSERT_GT(rokuSchema.size(), 0);

  // Test that we can parse the generated schema using OMOTE::JSON::GetDocument
  // This validates that schemas are properly formed JSON that rapidjson can work with
  auto schemaDocument = OMOTE::JSON::GetDocument(rokuSchema);

  // Should be a valid document (at least the structure is there)
  ASSERT_TRUE(schemaDocument.IsObject());
  ASSERT_TRUE(schemaDocument.HasMember("type"));
  ASSERT_TRUE(schemaDocument["type"].IsString());
  ASSERT_STREQ(schemaDocument["type"].GetString(), "object");

  ASSERT_TRUE(schemaDocument.HasMember("required"));
  ASSERT_TRUE(schemaDocument["required"].IsArray());

  ASSERT_TRUE(schemaDocument.HasMember("properties"));
  ASSERT_TRUE(schemaDocument["properties"].IsObject());
}

TEST(ObjectSchemaBuilderValidationTest, SchemaValidationIntegrationTest) {
  ASSERT_NE(rokuSchema.data(), nullptr);

  // Parse the generated schema
  auto schemaDocument = OMOTE::JSON::GetDocument(rokuSchema);
  ASSERT_TRUE(schemaDocument.IsObject());

  // Test a valid configuration
  std::string validConfigJson = R"({
    "ip_address": "192.168.1.100",
    "name": "My Roku"
  })";

  auto validConfig = OMOTE::JSON::GetDocument(validConfigJson);
  ASSERT_TRUE(validConfig.IsObject());

  // Test an invalid configuration (missing required field)
  std::string invalidConfigJson = R"({
    "ip_address": "192.168.1.100"
  })";

  auto invalidConfig = OMOTE::JSON::GetDocument(invalidConfigJson);
  ASSERT_TRUE(invalidConfig.IsObject());

  ASSERT_TRUE(OMOTE::JSON::IsJsonValid(validConfig, rokuSchema));    // Should pass validation
  ASSERT_FALSE(OMOTE::JSON::IsJsonValid(invalidConfig, rokuSchema)); // Should fail validation due to missing "name" field
}