name: ESP32 Build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Set pip constraints for ESP-IDF
        run: echo "PIP_CONSTRAINT=${{ github.workspace }}/Platformio/esp-idf-constraints.txt" >> $GITHUB_ENV
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Prepare PlatformIO environments
        working-directory: ./Platformio
        run: pio pkg install

      - name: Build Rev_1 Hardware
        working-directory: ./Platformio
        run: pio run --environment esp32_Rev1

      - name: Build Rev_5 Hardware
        working-directory: ./Platformio
        run: pio run --environment esp32_Rev5

      - name: Build Rev_5_3661 Hardware
        working-directory: ./Platformio
        run: pio run --environment esp32_Rev5_3661
